---
manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: domains
    default_ttl: 3600
    enforce_order: True
  route53:
    class: octodns_route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID 
    secret_access_key: env/AWS_SECRET_ACCESS_KEY 

zones:
  skunkw0rks.io.:
    sources:
      - config
    targets:
      - route53
  michaelmcallister.org.:
    sources:
      - config
    targets:
      - route53
  sknk.ws.:
    sources:
      - config
    targets:
      - route53
  michaelmcallister.net.:
    sources:
      - config
    targets:
      - route53
  skunkworks.consulting.:
    sources:
      - config
    targets:
      - route53
